/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useRef, useMemo } from 'react'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'
import { useGraph } from '@react-three/fiber'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

const Developer = ({ animationName = 'idle', ...props }) => {
  const group = useRef()

  const { scene } = useGLTF('/models/animations/developer.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const { animations: idleAnimation } = useFBX('/models/animations/idle.fbx')
  const { animations: saluteAnimation } = useFBX('/models/animations/salute.fbx')
  const { animations: clappingAnimation } = useFBX('/models/animations/clapping.fbx')
  const { animations: victoryAnimation } = useFBX('/models/animations/victory.fbx')

  // 1. Use useMemo to ensure this logic only runs when FBX files are loaded,
  // preventing the animation mixer from resetting on every render.
  const cleanedClips = useMemo(() => {
    // Helper: remove root/hips/pelvis position tracks from a clip
    function removeRootPositionTracks(clip) {
      if (!clip) return null
      const tracks = clip.tracks.filter((t) => {
        const name = t.name || ''
        const lower = name.toLowerCase()
        // keep non-position tracks
        if (!lower.includes('.position')) return true
        // drop tracks that target root/hip/pelvis (case-insensitive)
        if (/hip|hips|root|pelvis/.test(lower)) return false
        return true
      })
      return new THREE.AnimationClip(clip.name, clip.duration, tracks)
    }

    const clips = []
    if (idleAnimation?.[0]) clips.push(removeRootPositionTracks(idleAnimation[0]))
    if (saluteAnimation?.[0]) clips.push(removeRootPositionTracks(saluteAnimation[0]))
    if (clappingAnimation?.[0]) clips.push(removeRootPositionTracks(clappingAnimation[0]))
    if (victoryAnimation?.[0]) clips.push(removeRootPositionTracks(victoryAnimation[0]))

    // Assign friendly names
    if (clips[0]) clips[0].name = 'idle'
    if (clips[1]) clips[1].name = 'salute'
    if (clips[2]) clips[2].name = 'clapping'
    if (clips[3]) clips[3].name = 'victory'

    return clips
  }, [idleAnimation, saluteAnimation, clappingAnimation, victoryAnimation])

  // 2. Pass the stable 'cleanedClips' array to useAnimations
  const { actions } = useAnimations(cleanedClips, group)

  // 3. Handle Animation Transition
  useEffect(() => {
    const action = actions[animationName]

    if (!action) return

    // Fade in the new action and play it
    // .reset() ensures it starts from the beginning, but fadeIn handles the blending
    action.reset().fadeIn(0.5).play()

    // Cleanup: When the effect unmounts (animation changes), fade out the current action
    return () => {
      action.fadeOut(0.5)
    }
  }, [animationName, actions])

  return (
    <group
      ref={group}
      {...props}
      position={[0, -1.2, 0]}
      dispose={null}
      rotation={[Math.PI / 2, Math.PI, Math.PI]} // Fix FBX Axis
    >
      <group scale={2.2} position={[0, 1, 0.2]}>
        <skinnedMesh
          geometry={nodes.Hair.geometry}
          material={materials['N00_000_Hair_00_HAIR (Instance)']}
          skeleton={nodes.Hair.skeleton}
        />
        <primitive object={nodes.Root} />
        <skinnedMesh
          geometry={nodes['Body_(merged)'].geometry}
          material={materials['N00_000_00_Body_00_SKIN (Instance)']}
          skeleton={nodes['Body_(merged)'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Body_(merged)_1'].geometry}
          material={materials['N00_000_00_HairBack_00_HAIR (Instance)']}
          skeleton={nodes['Body_(merged)_1'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Body_(merged)_2'].geometry}
          material={materials['N00_005_01_Tops_01_CLOTH (Instance)']}
          skeleton={nodes['Body_(merged)_2'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Body_(merged)_3'].geometry}
          material={materials['N00_001_01_Bottoms_01_CLOTH (Instance)']}
          skeleton={nodes['Body_(merged)_3'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Body_(merged)_4'].geometry}
          material={materials['N00_004_01_Shoes_01_CLOTH (Instance)']}
          skeleton={nodes['Body_(merged)_4'].skeleton}
        />
        <skinnedMesh
          geometry={nodes['Body_(merged)_5'].geometry}
          material={materials['N00_010_01_Onepiece_00_CLOTH (Instance)']}
          skeleton={nodes['Body_(merged)_5'].skeleton}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)"
          geometry={nodes['Face_(merged)(Clone)'].geometry}
          material={materials['N00_000_00_FaceMouth_00_FACE (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)'].morphTargetInfluences}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)_1"
          geometry={nodes['Face_(merged)(Clone)_1'].geometry}
          material={materials['N00_000_00_EyeIris_00_EYE (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)_1'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)_1'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)_1'].morphTargetInfluences}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)_2"
          geometry={nodes['Face_(merged)(Clone)_2'].geometry}
          material={materials['N00_000_00_EyeHighlight_00_EYE (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)_2'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)_2'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)_2'].morphTargetInfluences}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)_3"
          geometry={nodes['Face_(merged)(Clone)_3'].geometry}
          material={materials['N00_000_00_Face_00_SKIN (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)_3'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)_3'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)_3'].morphTargetInfluences}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)_4"
          geometry={nodes['Face_(merged)(Clone)_4'].geometry}
          material={materials['N00_000_00_EyeWhite_00_EYE (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)_4'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)_4'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)_4'].morphTargetInfluences}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)_5"
          geometry={nodes['Face_(merged)(Clone)_5'].geometry}
          material={materials['N00_000_00_FaceBrow_00_FACE (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)_5'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)_5'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)_5'].morphTargetInfluences}
        />
        <skinnedMesh
          name="Face_(merged)(Clone)_6"
          geometry={nodes['Face_(merged)(Clone)_6'].geometry}
          material={materials['N00_000_00_FaceEyeline_00_FACE (Instance)']}
          skeleton={nodes['Face_(merged)(Clone)_6'].skeleton}
          morphTargetDictionary={nodes['Face_(merged)(Clone)_6'].morphTargetDictionary}
          morphTargetInfluences={nodes['Face_(merged)(Clone)_6'].morphTargetInfluences}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/animations/developer.glb')

export default Developer